version: '3.8'

services:
  kcz-db:
    image: postgres:16-alpine
    container_name: kcz-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kcz_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - kcz-network

  kcz-backend:
    build: .
    container_name: kcz-backend
    restart: unless-stopped
    depends_on:
      - kcz-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kcz-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    networks:
      - kcz-network

volumes:
  kcz_pgdata:

networks:
  kcz-network:
    driver: bridge
