spring.application.name=barbershop
spring.datasource.url=jdbc:postgresql://zephyr.proxy.rlwy.net:26062/railway
spring.datasource.username=postgres
spring.datasource.password=KsqFAbfVfpkgiohvaARVMTkUGJOvrSXL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=barbershop_super_secret_key_2024_change_in_production
jwt.expiration=86400000